name: Code Coverage

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout caustic
      uses: actions/checkout@v3
      with:
        path: caustic

    - name: Checkout torchinterp1d
      uses: actions/checkout@v3
      with:
        repository: aliutkus/torchinterp1d
        path: torchinterp1d

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest torch
        # Install torchinterp1d
        cd $GITHUB_WORKSPACE/torchinterp1d
        pip install .
        # Install other deps
        cd $GITHUB_WORKSPACE/caustic
        pip install -r requirements.txt
      shell: bash
    - name: Install Caustic
      run: |
        cd $GITHUB_WORKSPACE
        pip install -e .
        pip show caustic
      shell: bash
    - name: Test with pytest
      run: |
        cd $GITHUB_WORKSPACE
        pwd
        pytest --cov-report=xml --cov=src/caustic test/
        cat coverage.xml
      shell: bash
    - name: Upload coverage report to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: ${{ github.workspace }}/coverage.xml
        fail_ci_if_error: true