name: Code Coverage

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout caustic
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Record State
      run: |
        pwd
        echo github.ref is: ${{ github.ref }}
        echo GITHUB_SHA is: $GITHUB_SHA
        echo github.event_name is: ${{ github.event_name }}
        echo github workspace: ${{ github.workspace }}
        pip --version
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov torch wheel
        # Install deps
        cd $GITHUB_WORKSPACE
        pip install -r requirements.txt
      shell: bash
      
    - name: Install Caustic
      run: |
        cd $GITHUB_WORKSPACE
        pip install -e .[dev]
        pip show caustic
      shell: bash
    - name: Test with pytest
      run: |
        cd $GITHUB_WORKSPACE
        pwd
        pytest --cov-report=xml --cov=caustic test/
        cat coverage.xml
      shell: bash
    - name: Upload coverage report to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: ${{ github.workspace }}/coverage.xml
        fail_ci_if_error: false
