# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Unit Tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Checkout caustics
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Record State
        run: |
          pwd
          echo github.ref is: ${{ github.ref }}
          echo GITHUB_SHA is: $GITHUB_SHA
          echo github.event_name is: ${{ github.event_name }}
          echo github workspace: ${{ github.workspace }}
          pip --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov torch wheel
          # Install deps
          cd $GITHUB_WORKSPACE
          pip install -r requirements.txt
        shell: bash

      - name: Install Caustics
        run: |
          cd $GITHUB_WORKSPACE
          pip install -e .[dev]
          pip show caustics
        shell: bash

      - name: Test with pytest
        run: |
          cd $GITHUB_WORKSPACE
          pytest -vvv tests/
        shell: bash
